create table events (
    id bigint generated by default as identity,
    date timestamp not null,
    event_type_id integer not null,
    place_id integer not null,
    speaker varchar(50),
    title varchar(50) not null,
    primary key (id)
);

create table users (
    id bigint generated by default as identity,
    username varchar(45) not null,
    password varchar(60) not null,
    primary key (id)
);