CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    date TIMESTAMP NOT NULL,
    event_type_id INTEGER NOT NULL,
    place_id INTEGER NOT NULL,
    speaker VARCHAR(50),
    title VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
    );
CREATE TABLE IF NOT EXISTS  users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(45) NOT NULL,
    password VARCHAR(60) NOT NULL,
    PRIMARY KEY (id)
    );

INSERT INTO events (id, title, place_id, speaker, event_type_id, date )VALUES
(1, 'Test event 01', 3, 'Test Speaker 01', 0, '2030-01-01 11.00.00.000'),
(2, 'Test event 02', 4, 'Test Speaker 02', 2, '2030-01-02 12.00.00.000'),
(3, 'Test event 03 marker', 6, 'Test Speaker 03', 0, '2030-01-03 13.00.00.000'),
(4, 'Test event 04 marker', 4, 'Test Speaker 04', 3, '2030-01-04 14.00.00.000');

INSERT INTO users (id, username, password) VALUES (1, 'username','$2a$08$fL7u5xcvsZl78su29x1ti.dxI.9rYO8t0q5wk2ROJ.1cdR53bmaVG');