CREATE TABLE events
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date NOT NULL,
    title character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ticket_price double precision NOT NULL,
    CONSTRAINT events_pkey PRIMARY KEY (id)
)

CREATE TABLE tickets
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    category integer NOT NULL,
    event_id bigint NOT NULL,
    place integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT tickets_pkey PRIMARY KEY (id),
    CONSTRAINT tickets_place_check CHECK (place <= 500 AND place >= 1)
)

CREATE TABLE public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
)

CREATE TABLE public.accounts
(
    balance double precision,
    user_id bigint NOT NULL,
    CONSTRAINT accounts_pkey PRIMARY KEY (user_id),
    CONSTRAINT accounts_users_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
